#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# We lint the message, lint then fomat our code and finally test it before committing
# https://www.conventionalcommits.org/en/v1.0.0/#summary

npx --no -- commitlint --edit "$1"
